---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-7.2
    driver_config:
      box: opscode_debian-7.2.0_chef-provisionerless
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
  - name: centos-6.4
  - name: centos-7.0

suites:
  - name: emacs24
    run_list:
      - recipe[emacs24]
    attributes: {
      emacs24: {
        build_dir: "/opt/emacs"
      }
    }
